services:
  web:
    image: nekro/react-todo-app
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: react-todo-app
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: npm run dev